version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    container_name: titling-qualifications-app
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./etc/docker/nginx/default.conf:/etc/nginx/http.d/default.conf
      - ./etc/docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./etc/docker/supervisord.conf:/etc/supervisord.conf
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - titling-qualifications-app-net

networks:
  titling-qualifications-app-net:
    external:
      name: titling-qualifications-external
